<a href="https://colab.research.google.com/github/marciocardoso123/DataScience/blob/main/Numpy_%7CGuiaDeM%C3%A9todos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 05 - Métodos Importantes e Máscaras em Arrays

1. Métodos Importantes
    - ndim  >>  dimenção
    - shape >> tamanho
    - dtype >> tipo de dado
    - astype  >> denfinir novo tipo para array
    - min  >>  elemento minimo
    - max  >>  elemento máximo
    - argmin  >>  descobrir a posição do menor elemento
    - argmax  >>  descobrir a posição do maior elemento
    - sum >> soma
    - mean  >>  media
    - var  >>  variância
    - std  >>  desvio padrão
    - sort  >>  ordenar array
    - T  >>  transposição da matrix onde é linha vira coluna
    - reshape  >>  

2. Máscaras  >>  cria array boleano que define as posições do array todos elementos maiores que o prim elementos ou iguais  3   [a>=3]
todos elementos que são divisiveis por 2  [a%2==0]

In [ ]:
import numpy as np

In [ ]:
array = np.random.randn(10)

In [ ]:
array

array([ 0.08750322,  0.21183463, -0.53803631, -0.53525066, -0.35165849,
        0.25678342, -0.17898542,  1.64678876,  1.38647428,  0.7402866 ])

In [ ]:
mtx = np.random.randn(3, 3)

In [ ]:
mtx

array([[-0.16818146,  1.60420931, -0.28131795],
       [-0.60660859, -1.62667801,  1.31636158],
       [ 0.92640001, -0.15887591,  1.39391814]])

In [ ]:
array.ndim

1

In [ ]:
mtx.ndim

2

In [ ]:
array.shape

(10,)

In [ ]:
mtx.shape

(3, 3)

In [ ]:
array.dtype

dtype('float64')

In [ ]:
array.astype('int')

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
mtx.astype('int')

array([[ 0,  1,  0],
       [ 0, -1,  1],
       [ 0,  0,  1]])

In [ ]:
array.astype('bool')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
array[2] = 0
array

array([ 0.08750322,  0.21183463,  0.        , -0.53525066, -0.35165849,
        0.25678342, -0.17898542,  1.64678876,  1.38647428,  0.7402866 ])

In [ ]:
array.astype('bool')

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
array.min()

-0.5352506573560943

In [ ]:
array.max()

1.6467887634841545

In [ ]:
array.argmax()

7

In [ ]:
array.argmin()

3

In [ ]:
array.mean()

0.3263776334002013

In [ ]:
array.sum()

3.263776334002013

In [ ]:
array.var()

0.4677685990228955

In [ ]:
array.std()

0.6839361074127432

In [ ]:
np.sum(array)

3.263776334002013

In [ ]:
array

array([ 0.08750322,  0.21183463,  0.        , -0.53525066, -0.35165849,
        0.25678342, -0.17898542,  1.64678876,  1.38647428,  0.7402866 ])

In [ ]:
array.sort()

In [ ]:
array

array([-0.53525066, -0.35165849, -0.17898542,  0.        ,  0.08750322,
        0.21183463,  0.25678342,  0.7402866 ,  1.38647428,  1.64678876])

In [ ]:
mtx

array([[-0.16818146,  1.60420931, -0.28131795],
       [-0.60660859, -1.62667801,  1.31636158],
       [ 0.92640001, -0.15887591,  1.39391814]])

In [ ]:
mtx.T

array([[-0.16818146, -0.60660859,  0.92640001],
       [ 1.60420931, -1.62667801, -0.15887591],
       [-0.28131795,  1.31636158,  1.39391814]])

## Máscaras

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a[[False, True, False, True]]

array([2, 4])

In [ ]:
a >= 3

array([False, False,  True,  True])

In [ ]:
a[a >= 3]

array([3, 4])

In [ ]:
a[a % 2 == 0]

array([2, 4])

In [ ]:
a % 2 == 0

array([False,  True, False,  True])

In [ ]:
print(a)

[1 2 3 4]
